export const GAME_EVENTS = {
  // Connection & Presence lifecycle
  PLAYER_CONNECTED: 'PLAYER_CONNECTED',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  PLAYER_ONLINE: 'PLAYER_ONLINE',
  PLAYER_OFFLINE: 'PLAYER_OFFLINE',
  PLAYER_STATUS_CHANGED: 'PLAYER_STATUS_CHANGED',

  // Matchmaking queue & rooms
  QUEUE_JOINED: 'QUEUE_JOINED',
  QUEUE_LEFT: 'QUEUE_LEFT',
  QUEUE_STATUS: 'QUEUE_STATUS',
  MATCH_FOUND: 'MATCH_FOUND',
  PLAYER_JOINED: 'PLAYER_JOINED',

  // Game lifecycle
  GAME_STARTED: 'GAME_STARTED',
  GAME_STATE_UPDATED: 'GAME_STATE_UPDATED',
  GAME_ENDED: 'GAME_ENDED',

  // Gameplay actions & outcomes
  PLAYER_ACTION: 'PLAYER_ACTION',
  PLAYER_MOVE: 'PLAYER_MOVE',
  NODE_CAPTURED: 'NODE_CAPTURED',
  PLAYER_ATTACKED: 'PLAYER_ATTACKED',
  PLAYER_DEFENDED: 'PLAYER_DEFENDED',
  SCORE_UPDATED: 'SCORE_UPDATED',
  ACTION_REJECTED: 'ACTION_REJECTED',

  // Operations, Monitoring & Security
  MONITORING_METRICS_UPDATED: 'MONITORING_METRICS_UPDATED',
  MONITORING_EVENT: 'MONITORING_EVENT',
  MONITORING_SECURITY_EVENT: 'MONITORING_SECURITY_EVENT',
  MONITORING_SUBSCRIBE: 'MONITORING_SUBSCRIBE',
  MONITORING_UNSUBSCRIBE: 'MONITORING_UNSUBSCRIBE',
} as const;

export type GameEvent = typeof GAME_EVENTS[keyof typeof GAME_EVENTS];
